swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /

# Paths supported by the server application
paths:
  /books:
    get:
      operationId: api.renderBooks
      tags:
        - People
      summary: Read one person
      description: Read one person
