swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article

basePath: "/server"

# Paths supported by the server application
paths:
  /:
    get:
      operationId: "server.routing.home"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /stock_page:
      get:
        operationId: "server.models.stock.routing.stock_page"
        parameters:
          - name: stock_ticker
            description: stock_ticker
            in: query
            type: string
            required: true
        produces:
          - text/html
        responses:
          200:
            description: A list of users

  /sender:
    get:
      operationId: "server.routing.sender"
      produces:
        - text/html
      responses:
        200:
          description: A list of users


  /receive:
    get:
      operationId: "server.routing.receiver"
      parameters:
        - name: fname
          description: fname
          in: query
          type: string
          required: true
        - name: lname
          description: lname
          in: query
          type: string
          required: true
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /optiondecision:
    get:
      operationId: "server.models.portfolio.routing.optiondecision"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /track:
    get:
      operationId: "server.models.portfolio.routing.track"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option2:
    get:
      operationId: "server.models.portfolio.routing.option2"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option3parent:
    get:
      operationId: "server.models.portfolio.routing.option3parent"
      produces:
        - text/html
      responses:
        200:
          description: A list of users


  /contact:
    get:
      operationId: "server.routing.contact"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /aboutus:
    get:
      operationId: "server.routing.aboutus"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /sendcontact:
    get:
      operationId: "server.routing.sendcontact"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /portfolioview:
    get:
      operationId: "server.models.portfolio.routing.portfolioview"
      parameters:
        - name: timeHorizon
          description: timeHorizon
          in: query
          type: array
          items:
            type: number
        - name: investmentGoal
          description: investmentGoal
          in: query
          type: array
          items:
            type: number
        - name: riskAppetite
          description: riskAppetite
          in: query
          type: array
          items:
            type: string
        - name: initialInvestment
          description: initialInvestment
          in: query
          type: array
          items:
            type: number
        - name: optionType
          description: optionType
          in: query
          type: array
          items:
            type: string
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /portfoliosnapshot:
    get:
      operationId: "server.models.portfolio.routing.portfoliosnapshot"
      parameters:
        - name: histValues
          description: histValues
          in: query
          type: array
          items:
            type: array
            items:
              type: number
        - name: returnSinceInception
          description: returnSinceInception
          in: query
          type: array
          items:
            type: number
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /portfoliodashboard:
    get:
      operationId: "server.models.portfolio.routing.portfoliodashboard"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /saveportfolio:
    get:
      operationId: "server.models.portfolio.routing.saveportfolio"
      parameters:
        - name: portofolioName
          description: portfolioName
          in: query
          type: array
          items:
            type: array
            items:
              type: string
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /editportfolio:
    get:
      operationId: "server.models.portfolio.routing.editportfolio"
      parameters:
        - name: portofolioName
          description: portfolioName
          in: query
          type: string
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option3Parent:
    get:
      operationId: "server.models.portfolio.routing.option3Parent"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option3Purchase:
    get:
      operationId: "server.models.portfolio.routing.option3Purchase"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option3PurchaseA:
    get:
      operationId: "server.models.portfolio.routing.option3PurchaseA"
      produces:
        - text/html
      responses:
        200:
          description: A list of users


  /option3PurchaseB:
    get:
      operationId: "server.models.portfolio.routing.option3PurchaseB"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option3PurchaseC:
    get:
      operationId: "server.models.portfolio.routing.option3PurchaseC"
      produces:
        - text/html
      responses:
        200:
          description: A list of users



  /option3Retirement:
    get:
      operationId: "server.models.portfolio.routing.option3Retirement"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option3RetirementA:
    get:
      operationId: "server.models.portfolio.routing.option3RetirementA"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option3RetirementB:
    get:
      operationId: "server.models.portfolio.routing.option3RetirementB"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option3RetirementC:
    get:
      operationId: "server.models.portfolio.routing.option3RetirementC"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option3Wealth:
    get:
      operationId: "server.models.portfolio.routing.option3Wealth"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option3WealthA:
    get:
      operationId: "server.models.portfolio.routing.option3WealthA"
      produces:
        - text/html
      responses:
        200:
          description: A list of users

  /option3WealthB:
    get:
      operationId: "server.models.portfolio.routing.option3WealthB"
      produces:
        - text/html
      responses:
        200:
          description: A list of users
